####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TAZ, MAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  MAZ: 1
  TAZ: 310


# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : households.csv
    index_col: hh_id
  - tablename: persons
    filename : persons.csv
    rename_columns:
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
  - tablename: geo_cross_walk
    filename : geo_crosswalks.csv
  - tablename: MAZ_control_data
    filename : control_totals_maz.csv
  - tablename: TAZ_control_data
    filename : control_totals_taz.csv
  - tablename: REGION_control_data
    filename : control_totals_region.csv
  - tablename: geo_cross_walk
    filename : geo_crosswalks.csv
  - filename : repop_control_totals_maz.csv
    tablename: MAZ_control_data

# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: weight
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv

# Control Specification File Name for repop mode
# ------------------------------------------------------------------
repop_control_file_name: repop_controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - expanded_household_ids
    - summary_hh_weights
    - summary_MAZ_aggregate
    - summary_TAZ_aggregate


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - persons
      - hinc
      - hworkers
      - hh_id
  persons:
    filename: synthetic_persons.csv
    columns:
      - perid
      - age
      - hh_id


# Steps for base mode
# ------------------------------------------------------------------
# run_list:
  # steps:
    # - input_pre_processor
    # - setup_data_structures
    # - initial_seed_balancing
    # - meta_control_factoring
    # - final_seed_balancing
    # - integerize_final_seed_weights
    # - sub_balancing.geography=TAZ
    # - sub_balancing.geography=MAZ
    # - expand_households
    # - summarize
    # - write_tables
    # - write_synthetic_population

  #resume_after: expand_households

# Steps for repop mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor.repop
    - repop_setup_data_structures
    - initial_seed_balancing.final=true;repop
    - integerize_final_seed_weights.repop
    - repop_balancing
    # expand_households options are append or replace
    - expand_households.repop;append
    - summarize.repop
    - write_synthetic_population.repop
    - write_tables.repop

  resume_after: summarize
